// react/web/src/contentAA/ContentAA.tsx
import React, { Component, useEffect, useState } from 'react';
import MyService from '../service/Service';

import './ContentAA.css'

interface ContentAAProps {
    size: string;
    level: string;
    service: MyService
    foreground: string;
    background: string;
}

const myService = new MyService();

const ContentAA: React.FC<ContentAAProps> = ({ size, level, service, foreground, background }) => {

    document.title = "About"

    const [currentLevel, setCurrentLevel] = useState<string>('');
    useEffect(() => {
        setCurrentLevel('AA')
        service.updateCurrentLevel("AA")

        service.currentLocation = "../content"
    }, [])


    return (
        <div className="center">

            <div className="about">
                <h2 lang='eng'>Very Interesting Article</h2>
                <p lang="eng" style={{ color: foreground, backgroundColor: background }}
                    className={`${size === 'size1' ? 'about' : size === 'size2' ? 'about-two' : 'about-half'}`}>
                    This Website is supposed to be an Implementation test of the WCAG 2.1 Guideline
                    It is structured as 3 in 1 Website. This means there are 3 versions of every Component and workflow.
                    Each component is supposed to achieve the full confrormance for every Conformance Level.
                    These Levels being the levels A, AA and AAA
                    For more refferences about the Specification visit <a href="https://www.w3.org/TR/WCAG21/"
                        target="_self" className={`${size === 'size1' ? 'a-one' : size === 'size2' ? 'a-two' : 'a-half'}`}>WCAG
                        2.1</a> official Specification from W3C
                </p>
            </div>
        </div >
    );
}

export default ContentAA;

// angular/web/src/app/content-aa/content-aa.component.ts
import { Component, OnInit } from '@angular/core';
import { LocationService } from '../service/location.service';
import { DataService } from '../service/data.service';
import { MenuItem } from 'primeng/api';

@Component({
  selector: 'app-content-aa',
  templateUrl: './content-aa.component.html',
  styleUrls: ['./content-aa.component.css']
})
export class ContentAAComponent implements OnInit {


  constructor(private data: DataService, private location: LocationService) { }

  menuItems: MenuItem[] = [{ label: 'About', url: 'about/AAA', preserveFragment: true }];
  menuItem: MenuItem = { label: 'About', url: 'about', preserveFragment: true }

  size = 'size1'
  foreground: string;
  background: string;

  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message)
    this.data.currentForeground.subscribe(color => this.foreground = color);
    this.data.currenBackground.subscribe(color => this.background = color);
    document.title = "Content Level AA"
    this.location.currentLocation = 'content';
    document.documentElement.lang = 'en'
    this.data.changeLevel('AA');

    this.location.currentBc.subscribe(bc => this.menuItems = bc);


  }

}

<div class="center">
    <div class="about">
        <h2>Very Interesting Article</h2>
        <p lang="eng"
            [ngClass]="{'about' : size == 'size1', 'about-half' : size == 'size15', 'about-two' : size == 'size2' }">
            This Website is supposed to be an Implementation test of the WCAG 2.1 Guideline
            It is structured as 3 in 1 Website. This means there are 3 versions of every Component and workflow.
            Each component is supposed to achieve the full confrormance for every Conformance Level.
            These Levels being the levels A, AA and AAA
            For more refferences about the Specification visit <a href="https://www.w3.org/TR/WCAG21/"
                target="_self">WCAG
                2.1</a> official Specification from W3C
        </p>
    </div>
</div>
