// angular/web/src/app/sub-content/sub-content.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from '../service/data.service';
import { Router } from '@angular/router';
import { LocationService } from '../service/location.service';

@Component({
  selector: 'app-sub-content',
  templateUrl: './sub-content.component.html',
  styleUrls: ['./sub-content.component.css']
})
export class SubContentComponent implements OnInit, OnDestroy {

  constructor(private data: DataService, private location: LocationService, private router: Router) {
  }

  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message)
    this.location.currentLocation = 'sub';
    this.menuHome = { icon: "pi pi-home" }
    this.location.appendMenu(this.menuItem);
    this.menuItems = this.location.breadcrumbLocation;
    document.title = "Subcontent Level A"
    document.documentElement.lang = 'en'
    this.data.changeLevel('A');

  }

  ngOnDestroy(): void {
    this.location.removeMenu();
  }

  menuItem: MenuItem = { label: 'home', url: 'sub/A' }
  menuItems: MenuItem[];
  menuHome: MenuItem;
  size: string;


  handleClick(link: string) {
    this.redirectToAnotherPage(link);
  }

  handleKeyDown(event: KeyboardEvent, link: string) {
    if (event.key === 'Enter') {
      this.redirectToAnotherPage(link);
    }
  }

  redirectToAnotherPage(link: string) {
    this.router.navigate(['/' + link]);
  }

}

<div class="contentContainer">
    <p-card (click)="handleClick('/content/A')" (keydown)="handleKeyDown($event, '/content/AA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of vienna" src="../../assets/pexels-chris-hepworth-16047549.jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }" lang="en">
            Subtopic 1</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            Very very interesting topic with lots of good aticles you should read its very cool yes indeed.
            there is a boat in this picture very cool no? its in vienna, very international, very mr world wide.
        </p>

    </p-card>
    <p-card (click)="handleClick('/content/A')" (keydown)="handleKeyDown($event, '/content/A')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of the dunes" src="../../assets/pexels-stijn-dijkstra-16747506 (1).jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }" lang="en">
            Subtopic 2</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            This is a very serious article. Its so serious in fact, that it coudnt be more fascinating.
            So get ready to be blown away by so much seriousness. really its very interesting to say the least.
        </p>

    </p-card>
    <p-card (click)="handleClick('/content/A')" (keydown)="handleKeyDown($event, '/content/A')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="topic of the fields" src="../../assets/pexels-josh-withers-16978839.jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }" lang="en">
            Subtopic 3</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            this isnt really a topic about underground the picture is overgorund kinda weird no? but anyways its still
            pretty.
            sun's shining and everything very nice yes yes. i go write more text now bye.
        </p>

    </p-card>
</div>

// react/web/src/subContent/SubContent.tsx
import React, { Component, useEffect, useState } from 'react';
import { Card } from 'primereact/card';
import gordon from '../assets/gordonPlant.jpg'
import chris from '../assets/pexels-chris-hepworth-16047549.jpg'
import christ from '../assets/pexels-christyn-reyes-13458334.jpg'
import josh from '../assets/pexels-josh-withers-16978839.jpg'
import stjin from '../assets/pexels-stijn-dijkstra-16747506 (1).jpg'
import MyService from '../service/Service';
import './SubContent.css'
import { useNavigate } from 'react-router-dom';

interface SubContentAProps {
    size: string;
    level: string;
    service: MyService
}


const SubContent: React.FC<SubContentAProps> = ({ size, level, service }) => {

    document.title = "Sub Level A"
    document.documentElement.lang = 'en'


    const navigate = useNavigate()

    const [currentLevel, setCurrentLevel] = useState<string>('');
    useEffect(() => {
        service.currentLocation = "../sub"
        setCurrentLevel('AA')
        service.updateCurrentLevel(currentLevel)
    }, [])

    function handleClick(link: string) {
        navigate(link)
    }



    const headerGordon = (
        <img alt="Card" aria-label='Picture of a peer' src={gordon} />
    );
    const headerChris = (
        <img alt="Card" aria-label='Picture of the Donau' src={chris} />
    );
    const headerChrist = (
        <img alt="Card" aria-label="Picture of a lake" src={christ} />
    );
    const headerJosh = (
        <img alt="Card" aria-label='Picture of the fields' src={josh} />
    );
    const headerStjin = (
        <img alt="Card" aria-label='Picture of the dunes' src={stjin} />
    );
    return (
        <div>
            <div className='contentContainer' tabIndex={-1}>
                <div className="card" >
                    <Card onClick={() => handleClick("/content/A")} onKeyDown={(e) => e.key === 'Enter' ? navigate('/content/A') : null} title="Seaturtles" subTitle="Very interesting" tabIndex={0} header={headerChris} >
                        <p>
                            This is a atricle so fascinating. its about turtles, because turtles are very cool.
                            they have a big shell like the gas station. ok yes this is a very interesting article so go ahead and read
                            it. thank you.
                        </p>
                    </Card>
                </div>
                <div className="card" >
                    <Card onClick={() => handleClick("/content/A")} onKeyDown={(e) => e.key === 'Enter' ? navigate('/content/A') : null} title="Technology" subTitle="Very interesting" header={headerChrist} tabIndex={0}>
                        <p >
                            this isnt really a topic about underground the picture is overgorund kinda weird no? but anyways its still
                            pretty.
                            sun's shining and everything very nice yes yes. i go write more articles now bye.
                        </p>
                    </Card>
                </div>
                <div className="card" >
                    <Card title="Underground" subTitle="Very interesting" onClick={() => handleClick("/content/AA")} header={headerJosh} onKeyDown={(e) => e.key === 'Enter' ? navigate('/sub/A') : null} tabIndex={0}>
                        <p >
                            Animals are cool, because they have fur sometimes. But sometimes they dont which is also cool. Sometimes
                            they live
                            underwater thats crazy isnt it? Go ahead and look at these articles.
                        </p>
                    </Card>
                </div>
            </div >
        </div>
    );
}

export default SubContent;
