// angular/web/src/app/register-aa/register-aa.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../service/data.service';
import { LocationService } from '../service/location.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register-aa',
  templateUrl: './register-aa.component.html',
  styleUrls: ['./register-aa.component.css', "../../../src/styles.css"]
})
export class RegisterAAComponent implements OnInit {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  birthday: Date;
  validated: boolean;
  isAdult: boolean;
  firstNameExists: boolean;
  lastNameExistst: boolean;
  userNameExistst: boolean;
  emailValid: boolean;
  up: boolean;
  readonly emailRegex: RegExp = /^.*@hft.de$/;

  size: string;

  constructor(private data: DataService, private location: LocationService, private router: Router) {
    this.firstName = '';
    this.lastName = '';
    this.username = '';
    this.email = '';
    this.validated = false;
    this.up = true;
  }
  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message);
    this.location.currentLocation = 'register';
    document.title = "Register Level AA"
    document.documentElement.lang = 'en'
    this.data.changeLevel('AA');


  }

  validate(): boolean {
    if (this.firstNameExists && this.lastNameExistst &&
      this.emailValid && this.isAdult) {
      this.validated = true;
      return true;
    }
    return false;
  }

  checkEmailValid(mail: string): void {
    this.emailValid = this.emailRegex.test(mail);
    this.validate();
  }

  checkName(): void {
    if (this.firstName != '') {
      this.firstNameExists = true;
      console.log("first name exists: " + this.firstNameExists)
    } else {
      this.firstNameExists = false;
    }
    if (this.lastName != '') {
      this.lastNameExistst = true;
      console.log("lastname exists: " + this.lastNameExistst)
    } else {
      this.lastNameExistst = false;
    }
    if (this.username != '') {
      this.userNameExistst = true;
      console.log("lastname exists: " + this.userNameExistst)
    } else {
      this.userNameExistst = false;
    }
    this.validate()
  }

  checkAge(birth: Date): void {
    var today = new Date();
    var age = today.getFullYear() - birth.getFullYear();
    var month = today.getMonth() - birth.getMonth();
    if (month < 0 || (month === 0 && today.getDate() < birth.getDate())) {
      age--;
    }
    console.log("age: " + age)
    if (age >= 18) {
      this.isAdult = true;
    } else
      this.isAdult = false;
    this.validate()
  }

  onSubmit(url: string) {
    this.router.navigate([url])
  }
}

<h1>Register Level AA</h1>
<div class="center">
    <div class="p-fluid" id="form">
        <div class="col-2">
            <label for="firstName"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">Fistname:</label>
            <label *ngIf="!firstNameExists"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div class="col w-full">
                <input autocomplete="name" [attr.aria-required]="true" [attr.aria-invalid]="!firstNameExists"
                    (ngModelChange)="checkName()" id="firstName" aria-label="input firstName" pInputText type="text"
                    [(ngModel)]="firstName" />
            </div>
        </div>

        <div class="col-2">
            <label for="lastName"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
                Lastname:</label>
            <label *ngIf="!lastNameExistst"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div>
                <input autocomplete="family-name" [attr.aria-required]="true" [attr.aria-invalid]="!lastNameExistst"
                    (ngModelChange)="checkName()" id="lastName" aria-label="input lastName" pInputText type="text"
                    [(ngModel)]="lastName" />
            </div>
        </div>

        <div class="col-2">
            <label for="email"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">E-Mail:</label>
            <label *ngIf="!email"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required </label>
            <div>
                <input [attr.aria-required]="true" [attr.aria-invalid]="!emailValid" pInputText id="email"
                    autocomplete="email" (change)="checkEmailValid(email)" aria-label="input email" pInputText
                    type="email" [(ngModel)]="email" />
            </div>
            <label *ngIf="!emailValid"
                [ngClass]="{'error-suggestion-one' : size == 'size1', 'error-suggestion-half' : size == 'size15', 'error-suggestion-two' : size == 'size2', }">email
                must be @hft.de</label>
        </div>

        <div class="col-2">
            <label for="username"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">Username:</label>
            <label *ngIf="!userNameExistst"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div>
                <input [attr.aria-required]="true" [attr.aria-invalid]="!userNameExistst" (ngModelChange)="checkName()"
                    autocomplete="username" id="username" aria-label="input username" pInputText type="username"
                    [(ngModel)]="username" />
            </div>
        </div>

        <div class="col-2" tabindex="-1">
            <label for="birthday"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">Birthday:</label>
            <label *ngIf="!isAdult"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div>
                <p-calendar
                    [ngClass]="{'calendar-one': size === 'size1', 'calendar-half': size === 'size15', 'calendar-two': size === 'size2'}"
                    [attr.aria-required]="true" [attr.aria-invalid]="!isAdult" (onSelect)="checkAge(birthday)"
                    #myCalendar aria-label="input birthday" name="date" [(ngModel)]="birthday"
                    [showIcon]="true"></p-calendar>
            </div>
            <label *ngIf="!emailValid"
                [ngClass]="{'error-suggestion-one' : size == 'size1', 'error-suggestion-half' : size == 'size15', 'error-suggestion-two' : size == 'size2', }">must
                be 18 years old</label>
        </div>

        <label
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">*
            red marked fields are required</label>

        <div class="buttoncontainer">
            <div class="left">
                <p-button (onClick)="onSubmit('/main/AA')"
                    [ngClass]="{'button-one' : size == 'size1', 'button-half' : size == 'size15', 'button-two' : size == 'size2', }"
                    pRipple aria-label="submit register form" [disabled]="!validated" label="Submit"></p-button>
            </div>
            <div class="right">
                <p-button (onClick)="onSubmit('/main/AA')"
                    [ngClass]="{'button-one' : size == 'size1', 'button-half' : size == 'size15', 'button-two' : size == 'size2', }"
                    router-l aria-label="cancel register form" label="Cancel"></p-button>
            </div>
        </div>
    </div>
</div>

// react/web/src/registerAA/RegisterAA.tsx
import React, { Component, useEffect, useState } from 'react';
import MyService from '../service/Service';
import './RegisterAA.css'
import { InputText } from 'primereact/inputtext';
import { Calendar, CalendarChangeEvent } from 'primereact/calendar';
import { Button } from 'primereact/button';
import { useNavigate } from 'react-router-dom';
import { off } from 'process';






interface RegisterAAProps {
    size: string;
    level: string;
    service: MyService;
}

const RegisterAA: React.FC<RegisterAAProps> = ({ service, size, level }) => {

    const navigate = useNavigate()

    const [firstName, setfirstName] = useState('');
    const [lastname, setlastname] = useState('');
    const [username, setusername] = useState('');
    const [email, setemail] = useState('');
    const [date, setDate] = useState<string | Date | Date[] | null>(null);

    const [userNameExistst, setUserNameExists] = useState(false);
    const [isAdult, setIsAdult] = useState(false);
    const [firstNameExists, setFirstNameExists] = useState(false);
    const [lastNameExists, setLastNameExists] = useState(false);
    const [emailValid, setEmailValid] = useState(false);
    const [validated, setValidated] = useState(false);

    const emailRegex: RegExp = /^.*@hft.de$/;

    var ages = 0

    function checkAge(birth: any) {
        if (date != null) {
            console.log("age")
            var today = new Date();
            var age = today.getFullYear() - birth.getFullYear();
            var month = today.getMonth() - birth.getMonth();
            if (month < 0 || (month === 0 && today.getDate() < birth.getDate())) {
                age--;
            }
            if (age >= 18) {
                setIsAdult(true);
            } else
                setIsAdult(false);
            validate()
            ages = age
        }
    }

    function checkEmailValid(mail: string): void {
        setEmailValid(emailRegex.test(mail));
        validate();
    }

    function validate(): boolean {
        console.log("validating")
        if (firstNameExists && lastNameExists &&
            emailValid) {
            setValidated(true)
            return true;
        }
        return false;
    }

    function checkName(): void {
        if (firstName !== '') {
            setFirstNameExists(true);
        } else {
            setFirstNameExists(false);
        }
        if (lastname !== '') {
            setLastNameExists(true);
        } else {
            setLastNameExists(false);
        }
        if (username !== '') {
            setUserNameExists(true);
        } else {
            setUserNameExists(false);
        }
        validate();
    }

    useEffect(() => {
        document.title = 'Register AA'
        document.documentElement.lang = 'en'
        service.currentLocation = '../register'
        service.updateCurrentLevel('AA')

    })

    var menu = [{}]

    useEffect(() => {
        checkName()
        checkEmailValid(email)
        checkAge(date)
    }, [username, firstName, lastname, email, date]);

    return (
        <div lang='en' title='register'>
            <h2>Register Level AA</h2>
            <div className='center'>
                <div id='form'>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Fistname:</label>

                            {!firstNameExists && <label className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`} tabIndex={0} >* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText spellCheck={'true'} lang='en' tabIndex={0} role='name' aria-labelledby='input firstname' aria-required={true} aria-onInvalid={!firstNameExists} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} value={firstName} onChange={(e) => setfirstName(e.target.value)} />
                            </div>
                        </div>
                    </div>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='lastname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Lastname:</label>

                            {!lastNameExists && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`} >* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText spellCheck={true} lang='en' tabIndex={0} aria-required={true} aria-onInvalid={!lastNameExists} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} role='name' aria-labelledby='input firstname' value={lastname} onChange={(e) => setlastname(e.target.value)} />
                            </div>
                        </div>
                    </div>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Username:</label>

                            {!userNameExistst && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText autoComplete='name' spellCheck={true} lang='en' aria-required={true} aria-onInvalid={!userNameExistst} tabIndex={0} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} role='name' aria-labelledby='input firstname' value={username} onChange={(e) => { setusername(e.target.value); checkName() }} />
                            </div>
                        </div>
                    </div>

                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Email:</label>

                            {!emailValid && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText spellCheck={true} lang='en' tabIndex={0} aria-required={true} aria-onInvalid={!emailValid} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} role='name' aria-labelledby='input firstname' value={email} onChange={(e) => setemail(e.target.value)} />
                            </div>
                        </div>
                        <div className='req' >
                            {!emailValid && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>email must be @hft.de</label>}

                        </div>
                    </div>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Birthday:</label>

                            {!isAdult && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className={`${size === 'size1' ? 'calendar-one' : size === 'size2' ? 'calendar-two' : 'calendar-half'}`}>
                            <div className="card flex justify-content-center">
                                <Calendar showIcon className="cal" value={date} aria-required={true} aria-onInvalid={!isAdult} onChange={(e: CalendarChangeEvent) => setDate(e.value as Date | null)} />
                            </div>
                        </div>
                        <div className='req' >
                            {!isAdult && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>must be 18 years old</label>}
                            <label
                                className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>*
                                red marked fields are required</label>
                        </div>

                    </div>

                    <div className='buttonContainer'>
                        <div className='left'>
                            <Button label='Submit' onClick={() => navigate('main/A')} disabled={!validated}></Button>
                        </div>
                        <div className='right'>
                            <Button onClick={() => navigate('main/A')} label='Cancel' id='cancelButton' aria-label='Cancel Form'></Button>
                        </div>
                    </div>
                </div>
            </div >
        </div >


    )
}

export default RegisterAA
