// react/web/src/contentAAA/ContentAAA.tsx
import React, { Component, useEffect, useState } from 'react';
import MyService from '../service/Service';
import stjin from '../assets/pexels-stijn-dijkstra-16747506 (1).jpg'

import './ContentAAA.css'

interface ContentAAAProps {
    size: string;
    level: State[];
    service: MyService
    foreground: string;
    background: string;
    animated: boolean
}

interface State {
    label: string;
    url: string;
    target: string;
}


const myService = new MyService();

const ContentAAA: React.FC<ContentAAAProps> = ({ animated, size, level, service, foreground, background }) => {

    document.title = "Content"
    document.documentElement.lang = 'en'

    var menuItem = { label: 'Article', url: document.location.pathname, target: '_self' }

    var [menuItems, setMenuItems] = useState<State[]>(level)



    const [currentLevel, setCurrentLevel] = useState<string>('');
    useEffect(() => {
        setCurrentLevel('AAA')
        service.updateCurrentLevel("AAA")
        service.currentLocation = "../content"
        service.currentBc.subscribe((menu) => setMenuItems(menu))
        var boold = menuItems.find(item => item.url === menuItem.url) !== undefined
        if (!boold) {
            menuItems.push(menuItem)
            console.log(menuItems)
            service.updateBc(menuItems)
        }
    }, [])





    return (
        <div className="center">

            <div className="about">
                <h2 lang='eng' style={{ color: foreground, backgroundColor: background }}>Very Interesting Article</h2>
                <p lang="eng" style={{ color: foreground, backgroundColor: background }}
                    className={`${size === 'size1' ? 'about' : size === 'size2' ? 'about-two' : 'about-half'}`}>
                    This Website is supposed to be an Implementation test of the WCAG 2.1 Guideline
                    It is structured as 3 in 1 Website. This means there are 3 versions of every Component and workflow.
                    Each component is supposed to achieve the full confrormance for every Conformance Level.
                    These Levels being the levels A, AA and AAA
                    For more refferences about the Specification visit <a href="https://www.w3.org/TR/WCAG21/"
                        target="_self" className={`${size === 'size1' ? 'a-one' : size === 'size2' ? 'a-two' : 'a-half'}`}>WCAG
                        2.1</a> official Specification from W3C
                </p>
            </div>
            <img src={stjin} alt="animated picture" className={`${animated === true ? 'animated' : 'size2'}`}></img>

        </div >
    );
}

export default ContentAAA;

// angular/web/src/app/content-aaa/content-aaa.component.ts
import { Component, OnDestroy, HostListener, OnInit } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from '../service/data.service';
import { LocationService } from '../service/location.service';
import { Router } from '@angular/router';


@Component({
  selector: 'app-content-aaa',
  templateUrl: './content-aaa.component.html',
  styleUrls: ['./content-aaa.component.css']
})

export class ContentAAAComponent implements OnInit {
  menuItems: MenuItem[];
  menuItem: MenuItem = { label: 'Article', url: 'content/AAA', preserveFragment: true }
  size: string;
  foreground: string;
  background: string;
  animated: boolean;
  constructor(private data: DataService, private location: LocationService, private router: Router) {
  }

  @HostListener('window:popstate')
  onPopState() {
    console.log('User clicked back button');
    document.body.style.backgroundColor = 'white';
  }

  ngOnInit(): void {
    document.title = "Content"
    document.documentElement.lang = 'en'
    this.data.currentMessage.subscribe(message => this.size = message)
    this.location.currentLocation = 'content';
    this.location.currentBc.subscribe(bc => this.menuItems = bc);
    console.log(this.menuItems)
    var boold = this.menuItems.find(item => item.url === this.menuItem.url) !== undefined
    if (!boold) {
      this.menuItems.push(this.menuItem)
      this.location.updateBc(this.menuItems)
    }
    this.data.currentForeground.subscribe(color => this.foreground = color);
    this.data.currenBackground.subscribe(color => this.background = color);
    this.data.currentAnimation.subscribe(a => this.animated = a)
    this.data.changeLevel('AAA');
    document.title = "Subcontent Level AAA"
    window.onpopstate = () => {
      console.log('User clicked back button');
      document.body.style.backgroundColor = 'white';
    };
  }



}

<div class="center">
    <div class="about">
        <h2>About this website</h2>
        <p lang="eng"
            [ngClass]="{'about' : size == 'size1', 'about-half' : size == 'size15', 'about-two' : size == 'size2' }">
            This Website is supposed to be an Implementation test of the WCAG 2.1 Guideline
            It is structured as 3 in 1 Website. This means there are 3 versions of every Component and workflow.
            Each component is supposed to achieve the full confrormance for every Conformance Level.
            These Levels being the levels A, AA and AAA
            For more refferences about the Specification visit <a href="https://www.w3.org/TR/WCAG21/"
                target="_self">WCAG
                2.1</a> official Specification from W3C
        </p>
        <img src="../../assets/pexels-stijn-dijkstra-16747506 (1).jpg" alt="animated picture"
            [ngClass]="animated ? 'animated' : 'notAnimated'" />
    </div>


</div>
