// angular/web/src/app/main-aaa/main-aaa.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from '../service/data.service';
import { Router } from '@angular/router';
import { LocationService } from '../service/location.service';

@Component({
  selector: 'app-main-aaa',
  templateUrl: './main-aaa.component.html',
  styleUrls: ['./main-aaa.component.css']
})
export class MainAAAComponent implements OnDestroy, OnInit {
  menuItems: MenuItem[] = [{ label: 'home', url: 'main/AAA', preserveFragment: true }];
  menuItem: MenuItem = { label: 'home', url: 'main/AAA', preserveFragment: true }
  menuHome: MenuItem;
  size: string;
  validated: boolean;
  isAdult: boolean;
  firstNameExists: boolean;
  lastNameExistst: boolean;
  userNameExistst: boolean;
  emailValid: boolean;

  foreground: string;
  background: string;

  readonly emailRegex: RegExp = /^.*@hft.de$/;


  constructor(private data: DataService, private location: LocationService, private router: Router) {
  }
  ngOnDestroy(): void {
    //this.location.removeMenu();
  }


  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message)
    this.location.currentLocation = 'main';
    this.menuHome = { icon: "pi pi-home" }
    this.location.updateBc(this.menuItems);
    this.menuItems = this.location.breadcrumbLocation;
    this.data.currentForeground.subscribe(color => this.foreground = color);
    this.data.currenBackground.subscribe(color => this.background = color);
    this.data.changeLevel('AAA');
    document.title = "Home Level A"
    document.documentElement.lang = 'en'
  }

  handleClick(link: string) {
    this.redirectToAnotherPage(link);
  }

  handleKeyDown(event: KeyboardEvent, link: string) {
    if (event.key === 'Enter') {
      this.redirectToAnotherPage(link);
    }
  }

  redirectToAnotherPage(link: string) {
    this.router.navigate(['/' + link]);
  }

  validate(): boolean {
    if (this.firstNameExists && this.lastNameExistst &&
      this.emailValid && this.isAdult) {
      this.validated = true;
      return true;
    }
    return false;
  }

  checkEmailValid(mail: string): void {
    this.emailValid = this.emailRegex.test(mail);
    this.validate();
  }

  getHeaderClass(): string {
    if (this.size == "size1") {
      return "headerClass-one"
    }
    if (this.size == "size15") {
      return "headerClass-half"
    }
    if (this.size == "size2") {
      return "headerClass-two"
    }
    return "headerClass-one";

  }
}

<div class="welcome">
    <h1 [ngStyle]="{ 'color': foreground, 'background-color': background  }" tabindex="0">Welcome</h1>
    <h2 [ngStyle]="{ 'color': foreground, 'background-color': background  }" tabindex="0">Home Level AAA</h2>
</div>
<div class="contentContainer" aria-label="Copntaine with content cards inside">
    <p-card (click)="handleClick('/sub/AAA')" (keydown)="handleKeyDown($event, '/sub/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template alt="picture" pTemplate="header">
            <img alt="picture of a pier" src="../../assets/gordonPlant.jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Sustainability</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">

            This is a very serious article. Its so serious in fact, that it coudnt be more fascinating.
            So get ready to be blown away by so much seriousness. really its very interesting to say the least.
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/AAA')" (keydown)="handleKeyDown($event, '/sub/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of vienna" src="../../assets/pexels-chris-hepworth-16047549.jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Seaturtles</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Very very interesting topic with lots of good aticles you should read its very cool yes indeed.
            there is a boat in this picture very cool no? its in vienna, very international, very mr world wide.
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/AAA')" (keydown)="handleKeyDown($event, '/sub/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of the dunes" src="../../assets/pexels-stijn-dijkstra-16747506 (1).jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Technology</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            This is a atricle so fascinating. its about turtles, because turtles are very cool.
            they have a big shell like the gas station. ok yes this is a very interesting article so go ahead and read
            it.
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/AAA')" (keydown)="handleKeyDown($event, '/sub/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="tpicture of the fields" src="../../assets/pexels-josh-withers-16978839.jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Underground</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            this isnt really a topic about underground the picture is overgorund kinda weird no? but anyways its still
            pretty.
            sun's shining and everything very nice yes yes. i go write more text now bye.
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/AAA')" (keydown)="handleKeyDown($event, '/sub/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of the lake" src="../../assets/pexels-christyn-reyes-13458334.jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Animals</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Animals are cool, because they have fur sometimes. But sometimes they dont which is also cool. Sometimes
            they live
            underwater thats crazy isnt it? Go ahead and look at these articles.
        </p>

    </p-card>

</div>

// react/web/src/mainAAA/MainAAA.tsx
import React, { Component, useEffect, useState } from 'react';
import { Card } from 'primereact/card';
import gordon from '../assets/gordonPlant.jpg'
import chris from '../assets/pexels-chris-hepworth-16047549.jpg'
import christ from '../assets/pexels-christyn-reyes-13458334.jpg'
import josh from '../assets/pexels-josh-withers-16978839.jpg'
import stjin from '../assets/pexels-stijn-dijkstra-16747506 (1).jpg'
import MyService from '../service/Service';
import { useNavigate } from 'react-router-dom';

import './MainAAA.css'

interface MainAAAProps {
    size: string;
    level: State[];
    service: MyService;
    foreground: string;
    background: string;
}


interface State {
    label: string;
    url: string;
    target: string;
}

const MainAAA: React.FC<MainAAAProps> = ({ service, size, level, foreground, background }) => {

    document.title = "Home Level AAA"
    document.documentElement.lang = 'en'

    var menuItem = { label: 'home', url: document.location.pathname, target: '_self' }
    var [menuItems, setMenuItems] = useState<State[]>(level)



    const [currentLevel, setCurrentLevel] = useState<string>('AAA');
    useEffect(() => {
        service.updateCurrentLevel(currentLevel)
        service.currentLocation = '../main'
        var raus = menuItems.find(item => item.url === "/sub/AAA") !== undefined
        var rein = menuItems.find(item => item.url === "/about") !== undefined
        if (raus || rein) {
            menuItems.pop()
            service.updateBc(menuItems)
        }
        var boold = menuItems.find(item => item.url === menuItem.url) !== undefined
        if (!boold) {
            menuItems.push(menuItem)
            console.log(menuItems)
            service.updateBc(menuItems)
        }
    }, [])

    const navigate = useNavigate()

    function handleClick(link: string) {
        navigate(link)
    }



    const headerGordon = (
        <img alt="Card" aria-label='Picture of a peer' src={gordon} />
    );
    const headerChris = (
        <img alt="Card" aria-label='Picture of the Donau' src={chris} />
    );
    const headerChrist = (
        <img alt="Card" aria-label="Picture of a lake" src={christ} />
    );
    const headerJosh = (
        <img alt="Card" aria-label='Picture of the fields' src={josh} />
    );
    const headerStjin = (
        <img alt="Card" aria-label='Picture of the dunes' src={stjin} />
    );
    return (
        <div>
            <div className="welcome" >
                <h1 tabIndex={0} style={{ color: foreground, backgroundColor: background }}>Welcome</h1>
                <h2 tabIndex={0} style={{ color: foreground, backgroundColor: background }} >Home Level AAA</h2>
            </div>
            <div className='contentContainer'>
                <div className="card">
                    <Card tabIndex={0} role='contentinfo' className='pip' onClick={() => handleClick('/sub/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/sub/AAA') : null}
                        title="Sustainability" subTitle="Very interesting" header={headerGordon} style={{ color: foreground, backgroundColor: background }}>
                        <p style={{ color: foreground, backgroundColor: background }}
                            className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`}>
                            Very very interesting topic with lots of good aticles you should read its very cool yes indeed.
                            there is a boat in this picture very cool no? its in vienna, very international, very mr world wide.
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card tabIndex={0} role='contentinfo' className='pip' onClick={() => handleClick('/sub/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/sub/AAA') : null}
                        title="Seaturtles" subTitle="Very interesting" header={headerChris} style={{ color: foreground, backgroundColor: background }} >
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            This is a atricle so fascinating. its about turtles, because turtles are very cool.
                            they have a big shell like the gas station. ok yes this is a very interesting article so go ahead and read
                            it. thank you.
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card tabIndex={0} role='contentinfo' className='pip' onClick={() => handleClick('/sub/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/sub/AAA') : null}
                        title="Technology" subTitle="Very interesting" header={headerChrist} style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card tabIndex={0} role='contentinfo' className='pip' onClick={() => handleClick('/sub/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/sub/AAA') : null}
                        title="Underground" subTitle="Very interesting" header={headerJosh} style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            this isnt really a topic about underground the picture is overgorund kinda weird no? but anyways its still
                            pretty.
                            sun's shining and everything very nice yes yes. i go write more articles now bye.
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card tabIndex={0} role='contentinfo' onClick={() => handleClick('/sub/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/sub/AAA') : null}
                        title="Animals" subTitle="Very interesting" header={headerStjin} className='pip' style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            Animals are cool, because they have fur sometimes. But sometimes they dont which is also cool. Sometimes
                            they live
                            underwater thats crazy isnt it? Go ahead and look at these articles.
                        </p>
                    </Card>
                </div>
            </div >
        </div>
    );
};

export default MainAAA;
