// angular/web/src/app/content/content.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../service/data.service';
import { Router } from '@angular/router';
import { MenuItem } from "primeng/api";
import { LocationService } from '../service/location.service';

@Component({
  selector: 'app-content',
  templateUrl: './content.component.html',
  styleUrls: ['./content.component.css']
})
export class ContentComponent implements OnInit {

  menuItems: MenuItem[];
  menuItem: MenuItem = { label: 'artikel', url: 'content/AAA', preserveFragment: true }
  size: string;
  foreground: string;
  background: string;
  constructor(private data: DataService, private location: LocationService, private router: Router) {
  }

  ngOnInit(): void {
    document.title = "Content"
    document.documentElement.lang = 'en'
    this.data.currentMessage.subscribe(message => this.size = message)
    this.location.currentLocation = 'content';
    this.location.currentBc.subscribe(bc => this.menuItems = bc);
    console.log(this.menuItems)

    this.data.currentForeground.subscribe(color => this.foreground = color);
    this.data.currenBackground.subscribe(color => this.background = color);
    this.data.changeLevel('A');
    document.title = "Subcontent Level A"
  }

}

<div class="center">
    <div class="about">
        <h2>Very Interesting Article</h2>

        <p lang="eng"
            [ngClass]="{'about' : size == 'size1', 'about-half' : size == 'size15', 'about-two' : size == 'size2' }">
            This Website is supposed to be an Implementation test of the WCAG 2.1 Guideline
            It is structured as 3 in 1 Website. This means there are 3 versions of every Component and workflow.
            Each component is supposed to achieve the full confrormance for every Conformance Level.
            These Levels being the levels A, AA and AAA
            For more refferences about the Specification visit <a href="https://www.w3.org/TR/WCAG21/"
                target="_self">WCAG
                2.1</a> official Specification from W3C
        </p>
    </div>
</div>

// react/web/src/content/Content.tsx
import React, { Component, useEffect, useState } from 'react';
import MyService from '../service/Service';

import './Content.css'

interface ContentProps {
    size: string;
    level: string;
    service: MyService
    foreground: string;
    background: string;
}

const myService = new MyService();

const Content: React.FC<ContentProps> = ({ size, level, service, foreground, background }) => {

    document.title = "About"

    const [currentLevel, setCurrentLevel] = useState<string>('');
    useEffect(() => {
        setCurrentLevel('A')
        service.updateCurrentLevel("A")

        service.currentLocation = "../content"
    }, [])





    return (
        <div className="center">

            <div className="about">
                <h2 lang='eng'>Very Interesting Article</h2>
                <p lang="eng" style={{ color: foreground, backgroundColor: background }}
                    className={`${size === 'size1' ? 'about' : size === 'size2' ? 'about-two' : 'about-half'}`}>
                    This Website is supposed to be an Implementation test of the WCAG 2.1 Guideline
                    It is structured as 3 in 1 Website. This means there are 3 versions of every Component and workflow.
                    Each component is supposed to achieve the full confrormance for every Conformance Level.
                    These Levels being the levels A, AA and AAA
                    For more refferences about the Specification visit <a href="https://www.w3.org/TR/WCAG21/"
                        target="_self" className={`${size === 'size1' ? 'a-one' : size === 'size2' ? 'a-two' : 'a-half'}`}>WCAG
                        2.1</a> official Specification from W3C
                </p>
            </div>
        </div >
    );
}

export default Content;
