// angular/web/src/app/sub-content-aaa/sub-content-aaa.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from '../service/data.service';
import { Router } from '@angular/router';
import { LocationService } from '../service/location.service';

@Component({
  selector: 'app-sub-content-aaa',
  templateUrl: './sub-content-aaa.component.html',
  styleUrls: ['./sub-content-aaa.component.css']
})
export class SubContentAAAComponent {

  menuItems: MenuItem[];
  menuItem: MenuItem = { label: 'content', url: document.location.pathname, preserveFragment: true }
  size: string;
  foreground: string;
  background: string;
  constructor(private data: DataService, private location: LocationService, private router: Router) {
  }

  ngOnDestroy(): void {
    this.location.removeMenu();
  }

  previousPath: string;
  getPreviousPath(): string {
    const referrerUrl: URL = new URL(document.referrer);
    return referrerUrl.pathname;
  }


  ngOnInit(): void {
    this.previousPath = this.getPreviousPath();
    console.log(this.previousPath)
    this.data.currentMessage.subscribe(message => this.size = message)
    this.location.currentLocation = 'sub';
    this.location.currentBc.subscribe(bc => this.menuItems = bc);
    var boold = this.menuItems.find(item => item.url === "content/AAA") !== undefined
    if (boold) {
      this.menuItems.pop()
      this.location.updateBc(this.menuItems)
    }
    var boold = this.menuItems.find(item => item.url === this.menuItem.url) !== undefined
    if (!boold) {
      this.menuItems.push(this.menuItem)
      this.location.updateBc(this.menuItems)
    }

    this.data.currentForeground.subscribe(color => this.foreground = color);
    this.data.currenBackground.subscribe(color => this.background = color);
    this.data.changeLevel('AAA');
    document.title = "Subcontent Level AAA"



  }

  handleClick(link: string) {
    this.redirectToAnotherPage(link);
  }

  handleKeyDown(event: KeyboardEvent, link: string) {
    if (event.key === 'Enter') {
      this.redirectToAnotherPage(link);
    }
  }

  redirectToAnotherPage(link: string) {
    this.router.navigate(['/' + link]);
  }
}

<div class="contentContainer">
    <p-card (click)="handleClick('/content/AAA')" (keydown)="handleKeyDown($event, '/content/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of vienna" src="../../assets/pexels-chris-hepworth-16047549.jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }" lang="en">
            Seaturtles</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            Very very interesting topic with lots of good aticles you should read its very cool yes indeed.
            there is a boat in this picture very cool no? its in vienna, very international, very mr world wide.
        </p>

    </p-card>
    <p-card (click)="handleClick('/content/AAA')" (keydown)="handleKeyDown($event, '/content/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of the dunes" src="../../assets/pexels-stijn-dijkstra-16747506 (1).jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }" lang="en">
            Technology</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            This is a very serious article. Its so serious in fact, that it coudnt be more fascinating.
            So get ready to be blown away by so much seriousness. really its very interesting to say the least.
        </p>

    </p-card>
    <p-card (click)="handleClick('/content/AAA')" (keydown)="handleKeyDown($event, '/content/AAA')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="picture of the fields" src="../../assets/pexels-josh-withers-16978839.jpg" />
        </ng-template>
        <h3 [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }" lang="en">
            Underground</h3>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            very
            Interesting</p>
        <p [ngStyle]="{ 'color': foreground, 'background-color': background  }" lang="en"
            [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }"
            lang="en">
            this isnt really a topic about underground the picture is overgorund kinda weird no? but anyways its still
            pretty.
            sun's shining and everything very nice yes yes. i go write more text now bye.
        </p>

    </p-card>
</div>

// react/web/src/subContentAAA/SubContentAAA.tsx
import React, { Component, useEffect, useState } from 'react';
import { Card } from 'primereact/card';
import gordon from '../assets/gordonPlant.jpg'
import chris from '../assets/pexels-chris-hepworth-16047549.jpg'
import christ from '../assets/pexels-christyn-reyes-13458334.jpg'
import josh from '../assets/pexels-josh-withers-16978839.jpg'
import stjin from '../assets/pexels-stijn-dijkstra-16747506 (1).jpg'
import MyService from '../service/Service';
import './SubContentAAA.css'
import { useNavigate } from 'react-router-dom';

interface SubContentAAAProps {
    size: string;
    level: State[];

    service: MyService
    foreground: string
    background: string
}

interface State {
    label: string;
    url: string;
    target: string;
}


const SubContentAAA: React.FC<SubContentAAAProps> = ({ size, level, service, foreground, background }) => {

    document.title = "Sub Level AAA"
    document.documentElement.lang = 'en'
    var menuItem = { label: 'content', url: document.location.pathname, target: '_self' }

    var [menuItems, setMenuItems] = useState<State[]>(level)


    const navigate = useNavigate()

    const [currentLevel, setCurrentLevel] = useState<string>('AAA');
    useEffect(() => {
        setCurrentLevel('AAA')
        service.updateCurrentLevel(currentLevel)
        service.currentBc.subscribe((menu) => setMenuItems(menu))
        service.currentLocation = "../sub"
        console.log("sub" + menuItems)
        var raus = menuItems.find(item => item.url === "/content/AAA") !== undefined
        if (raus) {
            menuItems.pop()
            service.updateBc(menuItems)
        }
        var boold = menuItems.find(item => item.url === menuItem.url) !== undefined
        if (!boold) {
            menuItems.push(menuItem)
            service.updateBc(menuItems)
        }
    }, [])

    function handleClick(link: string) {
        navigate(link)
    }



    const headerGordon = (
        <img alt="Card" aria-label='Picture of a peer' src={gordon} />
    );
    const headerChris = (
        <img alt="Card" aria-label='Picture of the Donau' src={chris} />
    );
    const headerChrist = (
        <img alt="Card" aria-label="Picture of a lake" src={christ} />
    );
    const headerJosh = (
        <img alt="Card" aria-label='Picture of the fields' src={josh} />
    );
    const headerStjin = (
        <img alt="Card" aria-label='Picture of the dunes' src={stjin} />
    );
    return (
        <div>
            <div className='contentContainer' tabIndex={-1}>
                <div className="card">
                    <Card tabIndex={0} className='pip' onClick={() => handleClick('/content/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/content/AAA') : null}
                        title="Seaturtles" subTitle="Very interesting" header={headerChris} style={{ color: foreground, backgroundColor: background }} >
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            This is a atricle so fascinating. its about turtles, because turtles are very cool.
                            they have a big shell like the gas station. ok yes this is a very interesting article so go ahead and read
                            it. thank you.
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card tabIndex={0} className='pip' onClick={() => handleClick('/content/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/content/AAA') : null}
                        title="Technology" subTitle="Vry interesting" header={headerChrist} style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            this isnt really a topic about underground the picture is overgorund kinda weird no? but anyways its still
                            pretty.
                            sun's shining and everything very nice yes yes. i go write more articles now bye.
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card tabIndex={0} className='pip' onClick={() => handleClick('/content/AAA')} onKeyDown={(e) => e.key === 'Enter' ? navigate('/content/AAA') : null}
                        title="Underground" subTitle="Very interesting" header={headerJosh} style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            Animals are cool, because they have fur sometimes. But sometimes they dont which is also cool. Sometimes
                            they live
                            underwater thats crazy isnt it? Go ahead and look at these articles.
                        </p>
                    </Card>
                </div>
            </div >
        </div>
    );
}

export default SubContentAAA;
